Revert "board: add persistent ram headers and tables"
This reverts commit 177bf47380a6f304be8e039c65b1af30693cb447.

Build fails with:
arch/arm/mach-msm/built-in.o: In function `apq8084_reserve':
:(.init.text+0x1d2c): undefined reference to `msm_reserve'